[tools]
## https://mise-tools.jdx.dev/tools/python
python = "3.13"
## https://mise-tools.jdx.dev/tools/uv
uv = "latest"
## https://github.com/aquaproj/aqua-registry/blob/main/pkgs/go-task/task/pkg.yaml
"aqua:go-task/task" = "latest"
## https://mise-tools.jdx.dev/tools/direnv
direnv = "latest"

## https://mise-tools.jdx.dev/tools/osv-scanner
"aqua:google/osv-scanner" = "latest"
## Trufflehog
"aqua:trufflesecurity/trufflehog" = "latest"
## Gitleaks
"aqua:gitleaks/gitleaks" = "latest"
